---
- name: Firewlld play
  hosts: web1
  become: yes
  tasks:
    - name: Firewlld allow https
      firewalld:
        source: 172.20.1.2
        service: https
        state: enabled
        zone: internal
        permanent: yes
    - servie:
        name: firewalld
        state: reloaded