---
- name: Create a cron job 
  hosts: node00
  tasks:
   - name: Create cron job
     cron:
       name: "yum update"
       minute: "5"
       hour: "8"
       weekday: "0"
       user: root
       job: yum -y update
       cron_file: /etc/cron.d/ansible_yum