---
- name: Download and extract from URL
  hosts: web1
  tasks:
    - name: Download and extract from URL
      unarchive:
       src: https://github.com/kodekloudhub/Hello-World/archive/master.zip
       dest: /root
       remote_src: yes