---
- name: Firewlld play
  hosts: web1
  become: yes
  tasks: 
    - name: Firewlld whitelist
      firewalld:
        source: 172.20.1.101
        state: enabled
        zone: internal
        permanent: yes
        immediate: yes