---
- name: First play
  hosts: node01
  become: true
  tasks:
    - name: Copy file
      ansible.builtin.lineinfile:
        path: /var/www/html/index.html
        line: "Welcome to KodeKloud Labs!"
        state: present
        insertbefore: BOF